name: Dockerize
on:
  push:
    branches:
      - master

jobs:
  dockerize_cpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build CPU Docker image
        run: docker build --push -f Dockerfile -t ghcr.io/binozo/go-stable-diffusion:latest .

  dockerize_cuda:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Cleanup GitHub bloat
        run: curl -s -L https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh | bash

      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Cuda Docker image
        run: docker build --push -f Dockerfile.cuda -t ghcr.io/binozo/go-stable-diffusion:cuda .

  dockerize_vulkan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Cuda Docker image
        run: docker build --push -f Dockerfile.vulkan -t ghcr.io/binozo/go-stable-diffusion:vulkan .