name: Dockerize
on:
  push:
    branches:
      - master

jobs:
  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build CPU Docker image
        run: docker build --push -f Dockerfile -t ghcr.io/binozo/go-stable-diffusion:latest .

      - name: Build Cuda Docker image
        run: docker build --push -f Dockerfile.cuda -t ghcr.io/binozo/go-stable-diffusion:cuda .